### ISSUE TITLE
AWS/OCP: Discovery tests failing with Submariner Globalnet env

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/lighthouse#398] opened 2020-12-03 13:32 UTC
**What happened**:
When e2e is run on Submariner Globalnet deployment on AWS/OCP, LH tests are failing.

[discovery] Test Service Discovery Across Clusters when there are active pods for a service in only one cluster 
  should not resolve the service on the cluster without active pods
  /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/service_discovery.go:51
STEP: Creating namespace objects with basename "discovery"
STEP: Generated namespace "e2e-tests-discovery-zxcmk" in cluster "cluster-e" to execute the tests in
STEP: Creating namespace "e2e-tests-discovery-zxcmk" in cluster "cluster-f"
STEP: Creating an Nginx Deployment on on "cluster-f"
STEP: Deleting namespace "e2e-tests-discovery-zxcmk" on cluster "cluster-e"
STEP: Deleting namespace "e2e-tests-discovery-zxcmk" on cluster "cluster-f"

• Failure [242.353 seconds]
[discovery] Test Service Discovery Across Clusters
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/service_discovery.go:22
  when there are active pods for a service in only one cluster
  /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/service_discovery.go:50
    should not resolve the service on the cluster without active pods [It]
    /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/service_discovery.go:51

    Failed to find pods for app nginx-demo. Status for pod "nginx-demo-79c9559645-4k42f" is Pending
    Unexpected error:                                                                                                                                                                         
        <*errors.errorString | 0xc00034e070>: {                                                                                                                                               
            s: "timed out waiting for the condition",                                                                                                                                         
        }                                                                                                                                                                                     
        timed out waiting for the condition                                                                                                                                                   
    occurred                                                                                                                                                                                  

    /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416

Summarizing 6 Failures:

[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod with HostNetworking connects via TCP to the globalIP of a remote service when the pod is on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/tcp/connectivity.go:47

[Fail] [discovery] Test Service Discovery Across Clusters when a pod tries to resolve a service in a remote cluster [It] should be able to discover the remote service successfully 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416

[Fail] [discovery] Test Service Discovery Across Clusters when a pod tries to resolve a service which is present locally and in a remote cluster [It] should resolve the local service 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416

[Fail] [discovery] Test Service Discovery Across Clusters when service export is created before the service [It] should resolve the service 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416

[Fail] [discovery] Test Service Discovery Across Clusters when there are no active pods for a service [It] should not resolve the service 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416

[Fail] [discovery] Test Service Discovery Across Clusters when there are active pods for a service in only one cluster [It] should not resolve the service on the cluster without active pods 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416

Ran 11 of 30 Specs in 1716.616 seconds
FAIL! -- 5 Passed | 6 Failed | 0 Pending | 19 Skipped

**What you expected to happen**:
All e2e tests should pass.

**Environment**:
- Submariner version (use `subctl version`): v0.8.0-rc0 
- Kubernetes version (use `kubectl version`): v1.18.3+47c0e71
- Cloud provider or hardware configuration: AWS with OCP 4.5.13
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): OpenShiftSDN, Libreswan, Globalnet
- Others:

**Comment by sridhargaddam** [comment] 2020-12-03 13:35
While e2e tests were running, the pods were crashing with the following error

```
Message:  container create failed: time="2020-12-03T13:23:45Z" level=error msg="container_linux.go:348: starting container process caused \"exec: \\\"/docker-entrypoint.sh\\\": permission denied\""
container_linux.go:348: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied"```

Events:
  Type     Reason          Age        From                                   Message
  ----     ------          ----       ----                                   -------
  Normal   Scheduled       <unknown>  default-scheduler                      Successfully assigned e2e-tests-discovery-rmp2h/nginx-demo-79c9559645-5j94c to ip-10-0-140-102.ec2.internal
  Normal   AddedInterface  65s        multus                                 Add eth0 [10.129.2.20/23]
  Warning  Failed          65s        kubelet, ip-10-0-140-102.ec2.internal  Error: container create failed: time="2020-12-03T13:22:57Z" level=error msg="container_linux.go:348: starting container process caused \"exec: \\\"/docker-entrypoint.sh\\\": permission denied\""
container_linux.go:348: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied"
  Warning  Failed  64s  kubelet, ip-10-0-140-102.ec2.internal  Error: container create failed: time="2020-12-03T13:22:58Z" level=error msg="container_linux.go:348: starting container process caused \"exec: \\\"/docker-entrypoint.sh\\\": permission denied\""
container_linux.go:348: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied"
  Warning  Failed  63s  kubelet, ip-10-0-140-102.ec2.internal  Error: container create failed: time="2020-12-03T13:22:59Z" level=error msg="container_linux.go:348: starting container process caused \"exec: \\\"/docker-entrypoint.sh\\\": permission denied\""
container_linux.go:348: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied"
  Warning  Failed  47s  kubelet, ip-10-0-140-102.ec2.internal  Error: container create failed: time="2020-12-03T13:23:15Z" level=error msg="container_linux.go:348: starting container process caused \"exec: \\\"/docker-entrypoint.sh\\\": permission denied\""
container_linux.go:348: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied"
  Warning  Failed  33s  kubelet, ip-10-0-140-102.ec2.internal  Error: container create failed: time="2020-12-03T13:23:29Z" level=error msg="container_linux.go:348: starting container process caused \"exec: \\\"/docker-entrypoint.sh\\\": permission denied\""
container_linux.go:348: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied"
  Warning  Failed  17s  kubelet, ip-10-0-140-102.ec2.internal  Error: container create failed: time="2020-12-03T13:23:45Z" level=error msg="container_linux.go:348: starting container process caused \"exec: \\\"/docker-entrypoint.sh\\\": permission denied\""
container_linux.go:348: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied"
  Normal   Pulling  4s (x7 over 65s)  kubelet, ip-10-0-140-102.ec2.internal  Pulling image "nginxinc/nginx-unprivileged:stable-alpine"
  Normal   Pulled   3s (x7 over 65s)  kubelet, ip-10-0-140-102.ec2.internal  Successfully pulled image "nginxinc/nginx-unprivileged:stable-alpine"
  Warning  Failed   3s                kubelet, ip-10-0-140-102.ec2.internal  Error: container create failed: time="2020-12-03T13:23:59Z" level=error msg="container_linux.go:348: starting container process caused \"exec: \\\"/docker-entrypoint.sh\\\": permission denied\""
container_linux.go:348: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied"

**Comment by vthapar** [comment] 2020-12-04 05:52
This was caused by bug in nginx stable-alpine image which we use for Lighthouse E2E. It has now been fixed https://github.com/nginxinc/docker-nginx-unprivileged/commit/87a2ae3deb137977cd3952b80bb5e499b8e3376c

**Comment by nyechiel** [comment] 2021-01-24 14:47
Closing as per the comment from @vthapar. Please re-open if this is still relevant.

**Closed by nyechiel** 2021-01-24 14:47 UTC
Labels: 0.8.0-testday, bug
